// /*
//  * FIREBASE AUTH ACTIONS
//  */
// export const LOGIN_WITH_PROVIDER_FIREBASE = 'LOGIN_WITH_PROVIDER_FIREBASE';
// export const REGISTER_FIREBASE_USER = 'REGISTER_FIREBASE_USER';
// export const LOGIN_FIREBASE_USER = 'LOGIN_FIREBASE_USER';
// export const FETCH_FIREBASE_USER = 'FETCH_FIREBASE_USER';
export const UPDATE_FIREBASE_USER = 'UPDATE_FIREBASE_USER';
export const CHANGE_FIREBASE_USER_PASSWORD = 'CHANGE_FIREBASE_USER_PASSWORD';
export const FIREBASE_PASSWORD_RESET_EMAIL = 'FIREBASE_PASSWORD_RESET_EMAIL';
// export const LOGOUT_FIREBASE_USER = 'LOGOUT_FIREBASE_USER';

// Auth
export const ALREADY_LOGIN = 'ALREADY_LOGIN';
export const ALREADY_LOGOUT = 'ALREADY_LOGOUT';

export const LOGIN_CHECK = 'LOGIN_CHECK';
export const SIGNUP = 'SIGNUP';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';

// Post
export const NEW_POST = 'NEW_POST';
export const UPDATE_POST = 'UPDATE_POST';
export const REMOVE_POST = 'REMOVE_POST';
export const CHANGE_DETAIL_TYPE = 'CHANGE_DETAIL_TYPE';

export const GET_USER_POSTS = 'GET_USER_POSTS';
